### ISSUE TITLE
Flickering keyboard navigation test

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular#11823]
## Description  
2 out of 3 [builds failed](https://github.com/IgniteUI/igniteui-angular/pull/11767) with this test:

```
IgxTreeGrid - Key Board Navigation #tGrid Navigation with scrolls should move to the top left/bottom right cell when navigate with Ctrl + Home/End keys FAILED
	Error: Expected false to be true.
	    at <Jasmine>
	    at Function.TreeGridFunctions [as verifyTreeGridCellSelected] (projects/igniteui-angular/src/lib/test-utils/tree-grid-functions.spec.ts:407:76)
	    at UserContext.<anonymous> (projects/igniteui-angular/src/lib/grids/tree-grid/tree-grid-keyBoardNav.spec.ts:573:13)
	    at Generator.next (<anonymous>)
	Error: Expected true to equal 147.
```

**Comment by zdrawku** [comment]
This problem is no longer present
