### ISSUE TITLE
Cannot read properties of undefined (reading 'ngModule') - Licensed version unit test error

### ISSUE THREAD

**Issue by mikerentmeister** [IgniteUI/igniteui-angular#11899]
## Description  
When using the licensed version of IgniteUI it's causing a simple component unit test to fail. I'm hoping that it's just a simple issue and I'm just missing some configuration setting or something.

 * igniteui-angular version: 14.0.5 (But we have been dealing with this issue in 13.x as well. We just hadn't tracked it down to the licensed package yet)
 * browser: N/A
 * Nx repo with two libs
 * Jest unit test

## Error stack trace
```
TypeError: Cannot read properties of undefined (reading 'ngModule')

      10 |   beforeEach(
      11 |     waitForAsync(() => {
    > 12 |       TestBed.configureTestingModule({
         |               ^
      13 |         declarations: [ToolbarFilterComponent],
      14 |         schemas: [NO_ERRORS_SCHEMA],
      15 |         imports: [

      at isModuleWithProviders (../../node_modules/@angular/core/fesm2020/core.mjs:24124:18)
      at expandModuleWithProviders (../../node_modules/@angular/core/fesm2020/core.mjs:24657:9)
          at Array.map (<anonymous>)
      at Function.get (../../node_modules/@angular/core/fesm2020/core.mjs:24224:26)
      at getNgModuleDef (../../node_modules/@angular/core/fesm2020/core.mjs:1142:25)
      at isNgModule (../../node_modules/@angular/core/fesm2020/core.mjs:24127:14)
      at transitiveScopesFor (../../node_modules/@angular/core/fesm2020/core.mjs:24549:9)
      at setScopeOnDeclaredComponents (../../node_modules/@angular/core/fesm2020/core.mjs:24513:30)
      at flushModuleScopingQueueAsMuchAsPossible (../../node_modules/@angular/core/fesm2020/core.mjs:24160:21)
      at TestBedRender3.checkGlobalCompilationFinished (../../node_modules/@angular/core/fesm2015/testing.mjs:26350:13)
      at TestBedRender3.configureTestingModule (../../node_modules/@angular/core/fesm2015/testing.mjs:26225:14)
      at Function.configureTestingModule (../../node_modules/@angular/core/fesm2015/testing.mjs:26072:30)
      at src/lib/toolbar-filter/toolbar-filter.component.spec.ts:12:15
      at _ZoneDelegate2.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at AsyncTestZoneSpec2.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4797:47)
      at ProxyZoneSpec2.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3827:43)
      at _ZoneDelegate2.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone3.runGuarded (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:180:51)
      at runInTestZone (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4943:33)
      at ../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4894:21
      at new ZoneAwarePromise2 (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1351:25)
      at ../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4893:24
      at _ZoneDelegate2.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec2.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate2.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone3.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)
```

## Steps to reproduce  

1. **The attached video also shows the repro steps**
2. Download the example repo zip
3. Install dependencies (I removed my .npmrc file with my credentials before uploading)
4. Try running the libs\common\src\lib\toolbar-filter\toolbar-filter.component.spec.ts test
5. Observe that the unit test fails with: Cannot read properties of undefined (reading 'ngModule')
6. Change the package.json to 'igniteui-angular' instead of @infragistics/igniteui-angular'
7. Update tsconfig.base.json to remove the typescript path for the licensed package
8. Install dependencies again
9. Run the unit tests for libs\common\src\lib\toolbar-filter\toolbar-filter.component.spec.ts again

## Result  

The unit test now passes

## Expected result  
The unit tests should not fail when using the licensed package

## Attachments  

[repro example lib.zip](https://github.com/IgniteUI/igniteui-angular/files/9168400/repro.example.lib.zip)

https://user-images.githubusercontent.com/18708788/180451472-51c3d318-32ba-42d8-bfd6-e4145b09266b.mp4

**Comment by ChronosSF** [comment]
@mikerentmeister , if you don't need the typescript path and can just import from '@infragistics\igniteui-angular' I think we can solve this. In that case the only problem I found was Jest not finding the module because it seems to be using the name from the amd-module comment in index.d.ts which we aren't replacing during the generation of the licensed package. This we can easily solve.

However, I am yet to be able to run the test with the defined path and importing from 'igniteui-angular'. My assumption is that it also needs `moduleNameMapper` in jest's config but again even adding config that looks correct (as in, having it any other way breaks the app in a different way) doesn't solve it and the test module still comes with undefined imports from igniteui-angular.

I tested both options with the Jasmine configuration we use internally (and also for out ig cli projects) and both seem to work without issues so I am inclined to think nx and/or Jest have issues with such typescript paths.

**Comment by mikerentmeister** [comment]
@ChronosSF - I replaced all references of 'igniteui-angular' to '@infragistics/igniteui-angular', and removed the path mapping from the tsconfig file. I am getting another error now, but I'm honestly not sure why I'm getting it because I removed all references to it. When you replace the paths with '@infragistics/igniteui-angular', are you getting this error?

![image](https://user-images.githubusercontent.com/18708788/181296174-fa92cb83-7e40-4c87-b04a-e65cd520a6de.png)

**Comment by ChronosSF** [comment]
Yes, this is what I mentioned we can fix easily. Try removing the tripple slash (///) comment from node_modules/@infragistics/igniteui-angular/index.d.ts

**Comment by mikerentmeister** [comment]
Still failing for me with that removed unfortunately.. =/

I also did an nx reset before running the unit test, just in case something was cached, to no avail

![image](https://user-images.githubusercontent.com/18708788/181299953-460f7fc6-d0eb-43cf-be59-24fee9946ede.png)

**Comment by ChronosSF** [comment]
I think I also needed to do `npx jest --clearCache`  

Anyhow, I'll prepare the project to share to you but I'll need some time to go back step by step and ensure I am not missing anything as it became I mess while I was trying to debug the issue with typescript paths.

**Comment by mikerentmeister** [comment]
`npx jest --clearCache did the trick for me`

You might want to look into updating this documentation with our findings for Jest: https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ignite-ui-licensing#some-additional-changes-might-have-to-be-made-in-your-project-source.

A solution with moduleNameMapper in the jest.config.ts might be beneficial for future devs as well.

![image](https://user-images.githubusercontent.com/18708788/181315194-692f2944-6d29-47c5-8d5a-66a04d1d48c1.png)

**Comment by ChronosSF** [comment]
Glad it worked.

Step 3 should be omittable from the next patch (14.0.10 expected on Monday) onward. Please, let me know when you are able to give it a try.

Yes, we'll update our docs with some additional information around this case. I'll keep this issue open to associate the updates with.

**Comment by mikerentmeister** [comment]
I have confirmed that 14.0.11 removes the need to edit the index.d.ts file
