### ISSUE TITLE
IgxGrid: Row drag not always working

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#11941]
## Description  
If you drag a row somewhere and then try to drag it again somewhere else then sometimes this doesn't work.

 * igniteui-angular version: 14.x
 * browser: Chrome

## Steps to reproduce  
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag#row-reordering-demo
1. Drag a row somewhere
2. Try to drag the same row again (you might have to try a few times)

## Result  
Sometimes the row can't be dragged again.

## Expected result  
The row should always be draggable.

## Attachments  
![2022-08-04_08h42_30](https://user-images.githubusercontent.com/46870283/182781335-4a9dd31c-1e97-40bb-9c21-f57f02109427.gif)

**Comment by dafo** [comment]
@Timmeeeey can you please tell me if you see any error in the Console when this issue is reproduced?

**Comment by Timmeeeey** [comment]
@dafo
Most of the time when dragging a row this error appears:

```
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at get ghostLeft [as ghostLeft] (infragistics-igniteui-angular.mjs:15278:43)
    at AnimationFrameAction.<anonymous> (infragistics-igniteui-angular.mjs:16091:17)
    at AnimationFrameAction._execute (AsyncAction.js:53:18)
    at AnimationFrameAction.execute (AsyncAction.js:41:28)
    at AnimationFrameScheduler.flush (AnimationFrameScheduler.js:11:33)
    at AnimationFrameAction.js:14:125
    at timer (zone.js:2378:41)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at invokeTask (zone.js:487:34)
```

This is the corresponding code in `IgxDragDirective`:
```
get ghostLeft() {
    return parseInt(this.ghostElement.style.left, 10) + this._ghostHostX;
}
```
