### ISSUE TITLE
Grid - RowEditable with no PrimaryKey throws exception in console

### ISSUE THREAD

**Issue by mddifilippo89** [IgniteUI/igniteui-angular#12652]
## Description  
Exception in console. Doesn't occur when "editable" is enabled per column. Only happens when row-editable is set to true on the grid without a primary key. 

## Steps to reproduce  

1. Run sample attached
2. Double click on a cell to enter edit mode
3. Check browser's console

## Result  
Uncaught TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at rne.position (combined.js:61:1365)
    at t.show (combined.js:41:27422)
    at t.open (combined.js:41:46954)
    at t.openRowOverlay (combined.js:63:2496)
    at t.beginRowEdit (combined.js:44:130389)
    at t.enterEditMode (combined.js:44:134481)
    at t._updateCRUDStatus (combined.js:63:82515)
    at t.activate (combined.js:63:80614)
    at HTMLElement.pointerdown (combined.js:63:72184)
    at d.invokeTask (combined.js:71:27766)
## Expected result  
No exception

## Attachment
[binding-composite-data.zip](https://github.com/IgniteUI/igniteui-webcomponents/files/9974742/binding-composite-data.zip)

**Comment by skrustev** [comment]
@mddifilippo89 This seems to be already fixed. Could make sure that its ok so we can close it
