### ISSUE TITLE
Jest tests errors about IgxCarouselComponent being accessed before initialization

### ISSUE THREAD

**Issue by fexxdev** [IgniteUI/igniteui-angular#15020]
## Description  
The `IgxCarouselComponent` causes a `ReferenceError: Cannot access 'IgxCarouselComponent' before initialization` error during testing, even though `IgxCarouselComponent` is not explicitly imported or used anywhere in the codebase. The error occurs when testing components that use other Ignite UI components, such as `IgxSwitchComponent`.

* **igniteui-angular version:** 
"@infragistics/igniteui-angular": "18.2.2",
"igniteui-angular-core": "18.1.1",
"igniteui-angular-excel": "18.1.1",
"igniteui-angular-spreadsheet": "18.1.1",
"igniteui-angular-charts": "18.1.1",
(everything is the latest package)

* **browser:** Not browser-specific; occurs during unit tests in the Angular testing environment.

## Steps to reproduce  

1. Create a component that imports and uses `IgxSwitchComponent` or other Ignite UI components (e.g., `IgxButtonDirective`, `IgxToggleDirective`).
2. Set up a unit test for this component using `@angular/core/testing` and `@testing-library/angular`.
3. Run the test.

## Result  
A `ReferenceError: Cannot access 'IgxCarouselComponent' before initialization` error appears in the test output, even though `IgxCarouselComponent` is not used directly. The error prevents tests from running successfully.

## Expected result  
The test should run without attempting to initialize or reference `IgxCarouselComponent`, as it is not explicitly imported or used in the test or the component code.

## Attachments  
Here is a sample error message:

```
ReferenceError: Cannot access ‘IgxCarouselComponent’ before initialization
at Object. (node_modules/@infragistics/igniteui-angular/fesm2022/infragistics-igniteui-angular.mjs:34362:172)
at Object. (src/app/feature-modules/forms/fields/j-custom-selection-field-editor/j-custom-selection-field-editor.component.ts:7:1)
at Object. (src/app/feature-modules/forms/fields/j-custom-selection-field-editor/j-custom-selection-field-editor.component.spec.ts:4:1)
```

This issue occurs in Angular unit tests for components that include Ignite UI components, even when `IgxCarouselComponent` is not part of the component or test dependencies.

**Comment by fexxdev** [comment]
Little update: i've tried to rollback to v18.1.17 and all tests pass. So it's a bug introduced with v18.2

**Comment by StefanIndustries** [comment]
we are also encountering this issue with Jest and Infragistics >18.1.17
This is currently preventing us from upgrading to Angular 19.

**Comment by eddiefrank** [comment]
any news or workarounds?

**Comment by eddiefrank** [comment]
the same here, that blocks us to update to Angular 19
