### ISSUE TITLE
igniteui-angular-charts throws exception in 18.1 versions

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#15173]
## Description  
When unit tests for a project containing igniteui-angular-charts is throwing the following error:

```console
TypeError: Cannot read properties of null (reading 'getExternal')
    at Function.pk (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:18668:27)
    at CrosshairLayer.pj (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:20094:32)
    at CrosshairLayer.q5 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:19666:30)
    at CrosshairLayer.q5 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:25681:19)
    at CrosshairLayer.q5 (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:27315:19)
    at CrosshairLayer.propertyUpdated (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:17829:89)
    at CrosshairLayer.raisePropertyChanged (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:18746:22)
    at CrosshairLayer.set c9 [as c9] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:20135:22)
    at XamDataChart.apply [as qx] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-charts/fesm2015/igniteui-angular-charts.js:3457:29)
    at SeriesCollection.ret [as collectionChanged] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/igniteui-angular-core/fesm2015/igniteui-an

```

 * igniteui-angular version: 18.1

## Steps to reproduce  

1. Use the attached sample and unzip it.
2. `npm i`
3. `ng test
[CRM App_angular-standalone.zip](https://github.com/user-attachments/files/18124777/CRM.App_angular-standalone.zip)
`

## Result  
Tests are failing, because of a problem coming from the chart. There isn't such an error, using 18.0:

```
    "igniteui-angular-charts": "~18.0.0",
    "igniteui-angular-core": "~18.0.0",
```

## Expected result  
No exception is thrown.

## Attachments  
[CRM App_angular-standalone.zip](https://github.com/user-attachments/files/18124780/CRM.App_angular-standalone.zip)

**Comment by gmurray81** [comment]
fixed in dev-tools/pullrequest/14798

**Comment by Lipata** [comment]
Thank you, @gmurray81!
