### ISSUE TITLE
[igx-grid][IE11] "Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges" is thrown when closing filtering row.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4764]
## Description  
"Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges" is thrown when closing filtering row.

 * igniteui-angular version: 7.2.8(7.2.6+)
 * browser: IE11

## Steps to reproduce  

1. Run the attached sample on IE11.
2. Open console.
3. Click a filter chip on the column "1".
3. Focus in the filter textbox.
4. Type something in the textbox. **But, you must not press Enter key**.
5. Click "閉じる" button.

## Result  
The following error was thrown.
>"Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
at debugUpdateDirectives (http://localhost:4200/vendor.js:65903:9)
at checkAndUpdateView (http://localhost:4200/vendor.js:65302:5)
at callWithDebugContext (http://localhost:4200/vendor.js:66172:9)
at debugCheckAndUpdateView (http://localhost:4200/vendor.js:65874:5)
at ViewRef_.prototype.detectChanges (http://localhost:4200/vendor.js:63683:13)
at Anonymous function (http://localhost:4200/vendor.js:139161:13)
at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:3113:13)
at onInvokeTask (http://localhost:4200/vendor.js:59285:17)
at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:3113:13)
at Zone.prototype.runTask (http://localhost:4200/polyfills.js:2886:21)"
![error-when-closing-filtering-row](https://user-images.githubusercontent.com/15909409/57633315-558cef80-75de-11e9-897f-ef9951a47eb0.gif)

## Expected result  
Any error should not be thrown.

## Attachments  
[igx-grid-closing-filtering-row-error.zip](https://github.com/IgniteUI/igniteui-angular/files/3173613/igx-grid-closing-filtering-row-error.zip)

**Comment by gedinakova** [comment]
Reproduced on IE11 and Edge.
