### ISSUE TITLE
Adding a `hierarchical-grid-custom` causes a TypeError

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6290]
## Description  
Adding a `hierarchical-grid-custom` causes a TypeError

 * igniteui-angular version: 4.3.2 (current as of December 4th, 2019)
 * browser: any, the error happens in the CLI

## Steps to reproduce  

1. `ig add hierarchical-grid-custom HierarchicalGridCustom`

## Result  
The `ig` utility reports the following
```shell
(node:22604) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'columnFeatures' of undefined
    at IgxHierarchicalGridTemplate.getSelectedFeatures (node_modules/igniteui-cli/templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.js:79:40)
    at IgxHierarchicalGridTemplate.generateFiles (node_modules/igniteui-cli/templates/angular/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.js:37:41)
    at Object.<anonymous> (node_modules/igniteui-cli/lib/commands/add.js:117:32)
    at Generator.next (<anonymous>)
    at node_modules/igniteui-cli/lib/commands/add.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/igniteui-cli/lib/commands/add.js:3:12)
    at Object.addTemplate (node_modules/igniteui-cli/lib/commands/add.js:108:16)
    at Object.<anonymous> (node_modules/igniteui-cli/lib/commands/add.js:98:31)
    at Generator.next (<anonymous>)
(node:22604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
No component 'HierarchicalGridCustom' is created.

## Expected result  
The output should be
```shell
✔ View 'HierarchicalGridCustom' added.
```
and the corresponding component is generated.

## Attachments  
None

**Comment by Lipata** [comment]
Hi, @catull. I'm transferring this issue to our CLI project and we will investigate it. Thank you!
