### ISSUE TITLE
ReferenceError: PointerEvent is not defined

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6407]
## Description
Test run issue, it builds fine otherwise.
I have a component, which references `IgxColumnComponent`.
The component's module imports `IgxGridModule`.
I use `jest` as test runner, not `karma`.

See definition below.

The spec test fails to run with
```log
 FAIL  src/app/pages/publication/list/publication-list2.component.spec.ts
  ● Test suite failed to run

    ReferenceError: PointerEvent is not defined

      1 | import { async, ComponentFixture, TestBed } from '@angular/core/testing';
      2 | import { NoopAnimationsModule } from '@angular/platform-browser/animations';
    > 3 | import { IgxGridModule } from 'igniteui-angular';
        | ^
      4 | import { PublicationList2Component } from './publication-list2.component';
      5 | 
      at node_modules/igniteui-angular/bundles/ng:/igniteui-angular/lib/slider/slider.component.ts:766:34
      at node_modules/igniteui-angular/bundles/ng:/igniteui-angular/lib/slider/slider.component.ts:60:1
      at node_modules/igniteui-angular/bundles/igniteui-angular.umd.js:2:68
      at Object.<anonymous> (node_modules/igniteui-angular/bundles/igniteui-angular.umd.js:5:2)
      at Object.<anonymous> (src/app/pages/publication/list/publication-list2.component.spec.ts:3:1)
```

 * igniteui-angular version: 9.0.0-beta.6
 * browser: all, this is a test issue

The same behaviour is experienced with Node JS 12.14.0 and 13.5.0, under Linux Mint 19.2 (64 bit).

## Steps to reproduce  

1. Create a new project w/ ignite CLI
2. create component with the content below.
3. build works
4. `npm run test` fails.

## Result  
Test fails.

## Expected result  
Test should run.
Why does it insist on the slider component ?

`slider.component.ts` at line 766 has a `PointerEvent` argument:

```typescript
    /**
     * @hidden
     */
    @HostListener('pointerdown', ['$event'])
    public onPointerDown($event: PointerEvent) {
        this.findClosestThumb($event);

        if (!this.thumbTo.isActive && this.thumbFrom === undefined) {
            return;
        }

        const activeThumb = this.thumbTo.isActive ? this.thumbTo : this.thumbFrom;
        activeThumb.nativeElement.setPointerCapture($event.pointerId);
        this.showSliderIndicators();

        $event.preventDefault();
    }
```
All other methods in `slider.component.ts` which have `$event` as argument DO NOT QUALIFY which type it represents.
Perhaps the fix is a simple change to

```typescript
    @HostListener('pointerdown', ['$event'])
    public onPointerDown($event) {
       // ...... same code as above
    }
```

## Attachments  
`publication-list.module.ts`:
```typescript
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { ApolloModule } from 'apollo-angular';
import { HttpLinkModule } from 'apollo-angular-link-http';
import { IgxGridModule } from 'igniteui-angular';
import { PublicationList2Component } from './publication-list2.component';

@NgModule({
  imports: [
    CommonModule,
    RouterModule,

    ApolloModule,
    HttpLinkModule,

    IgxGridModule,
  ],
  declarations: [PublicationList2Component],
  exports: [PublicationList2Component],
})
export class PublicationListModule {}
```

`publication-list2.component/ts`:

```typescript
import { Component, OnInit } from '@angular/core';
import { IgxColumnComponent } from 'igniteui-angular';
import { employeesData } from './localData';

@Component({
  selector: 'app-publication-list2',
  templateUrl: './publication-list2.component.html',
  styleUrls: ['./publication-list2.component.css']
})
export class PublicationList2Component implements OnInit {
  public localData: any[];
  title = 'PublicationList2';
  constructor() { }

  ngOnInit() {
    this.localData = employeesData;
  }

  public onColumnInit(column: IgxColumnComponent) {
    if (column.field === 'RegistererDate') {
      column.formatter = (date => date.toLocaleDateString());
    }
  }
}
```
`publication-list2.component.css` is empty

`publication-list2.component.html`:

```html
<p>igx-grid component with auto generated columns below and local data.</p>
<p>You can read more about configuring the igx-grid component in the 
<a href="https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/README.md" target="_blank">README</a> or the 
<a href="https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html" target="_blank">official documentation</a>.</p>
<igx-grid #grid1 [data]="localData" [autoGenerate]="true" (onColumnInit)="onColumnInit($event)" width="960px" height="550px" [paging]="true" >
</igx-grid>
```

`publication-list2.component.spec.ts`:
```typescript
import { async, ComponentFixture, TestBed } from '@angular/core/testing';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { IgxGridModule } from 'igniteui-angular';
import { PublicationList2Component } from './publication-list2.component';

describe('PublicationList2Component', () => {
  let component: PublicationList2Component;
  let fixture: ComponentFixture<PublicationList2Component>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ PublicationList2Component ],
      imports: [ NoopAnimationsModule, IgxGridModule ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(PublicationList2Component);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

**Comment by catull** [comment]
Created PR https://github.com/IgniteUI/igniteui-angular/pull/6414 to fix this error.

**Comment by Aleksandyr** [comment]
@catull Thanks for the contribution and the time you have spent over the problem, but it seems that the problem doesn't come from the library, which means that we will have to decline the PR you have made.

It turns out that the problem comes from a [jsdom ](https://github.com/jsdom/jsdom/issues/2527) which is used by **jest test runner**. That's why you can't reproduce it if you are using karma as a test runner.

You can workaround those problems, by mocking the events they don't support.
