### ISSUE TITLE
Hierarchical grid test is failing with Ivy false

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#7091]
## Description  
Hierarchical grid test is failing with Ivy false

 * igniteui-angular version: 9.1
 * browser: n/a

## Steps to reproduce  

Run test 'should allow navigating to start in child grid when child grid target row moves outside the parent view port.' with Ivy false

## Result  
the test is failing

## Expected result  
test should not have errors

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
Test fails correctly. The issue is that hierarchical row.cells returns incorrect collection of cell. Some of the returned cells no longer exist in DOM, which throws an error.

Can be reproduced in master in a hierarchical grid that has horizontal virtualization when Ivy is disabled.  

1) Disable ivy for samples:
"angularCompilerOptions": {
        "enableIvy": false
    }
2) Open hierarchicalGrid sample, go to "Sample three"
3) Scroll grid to the right edge.
4) Select cell and hit Ctrl+Home

Error is thrown:
Uncaught DOMException: Failed to execute 'selectNode' on 'Range': the given Node has no parent.
    at IgxGridSelectionService._moveSelectionChrome (http://localhost:4200/main.js:51424:15)
    at IgxGridSelectionService.keyboardStateOnFocus (http://localhost:4200/main.js:51281:22)
    at IgxHierarchicalGridCellComponent.activate (http://localhost:4200/main.js:28025:35)
    at IgxHierarchicalGridCellComponent.activate (http://localhost:4200/main.js:46796:15)
    at http://localhost:4200/main.js:42201:93
    at IgxHierarchicalGridComponent.executeCallback (http://localhost:4200/main.js:41192:9)
    at IgxHierarchicalGridComponent.navigateTo (http://localhost:4200/main.js:41096:18)
    at http://localhost:4200/main.js:41093:89
    at SafeSubscriber._next (http://localhost:4200/main.js:42490:17)
    at SafeSubscriber.__tryOrUnsub (http://localhost:4200/vendor.js:115307:16)
