### ISSUE TITLE
Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'

### ISSUE THREAD

**Issue by frankdenouter** [IgniteUI/igniteui-angular#84]
Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'

I have a grid defined <div data-ig-grid="licensingGridOptions" id="licensingGrid"></div>

All works well, but when I change the view (via angular-ui-routing) I get the error mentioned above.

It looks like the destroy is called twice on the element via the $broadcast?

See trace:
Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'
    at Function.error (http://localhost:3000/scripts/jquery-2.2.3.min.js:2:1813)
    at HTMLTableElement.<anonymous> (http://localhost:3000/scripts/jquery-ui.min.js:6:9075)
    at Function.each (http://localhost:3000/scripts/jquery-2.2.3.min.js:2:2861)
    at n.each (http://localhost:3000/scripts/jquery-2.2.3.min.js:2:845)
    at n.e.fn.(anonymous function) [as igGrid](http://localhost:3000/scripts/jquery-ui.min.js:6:8817)
    at http://localhost:3000/scripts/igniteui-angular.js:650:31
    at Scope.$broadcast (http://localhost:3000/scripts/angular.js:17552:28)
    at Scope.$destroy (http://localhost:3000/scripts/angular.js:17170:14)
    at g (http://localhost:3000/scripts/ui-bootstrap-tpls-1.3.2.min.js:8:21013)
    at processQueue (http://localhost:3000/scripts/angular.js:15961:28)

AngularJs 1.5.5
Ignite UI 16.1.20161.1009
jQuery 2.2.3
jQuery UI 1.11.4
Angular-ui-bootstrap 1.3.2

**Comment by skrustev** [comment]
@frankdenouter Can you provide a sample where this could be seen? I wasn't able to reproduce the it by switching views ,each view having a separate grid, with the 'angular-ui-router'.

**Comment by frankdenouter** [comment]
@skrustev , I made an example here: http://codepen.io/uc/pen/qapvog?editors=1011

By making the example, I also figured out the cause of the error: it was angular-ui-route. I'd used version 0.2.18. Using version 0.3.1 of angular-ui-route fixed it!

**Comment by frankdenouter** [comment]
Updating to the latest version of angular UI route prevented the error as stated above. But there is another scenario which causes the problem. In combination with a bootstrap-modal (an angular-ui-bootstrap) opening and closing a modal dialog with a grid causes: Error: cannot call methods on igGrid prior to initialization; attempted to call method 'destroy'

I've made an example here: http://codepen.io/uc/pen/xEjqAQ?editors=1011

**Comment by dkamburov** [comment]
This seems like an issue into the ui-modal dialog calling destroy of its child scopes, but I've improved the check when destroying element, which solves it.
